apiVersion: v1
kind: Service
metadata:
  labels:
    name: loadtestpython
  name: loadtestpython
spec:
  ports:
    - port: 5700
  selector:
    name: loadtestpython

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: loadtestpython
  name: loadtestpython
spec:
  template:
    metadata:
      labels:
        name: loadtestpython
    spec:
      containers:
      - name: loadtestpython
        image: vizzuality/loadtest-python-python:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: "128Mi"
        args:
          - start
        env:
          - name: PORT
            value: "5700"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://loadtestpython.default.svc.cluster.local:5700
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 5700

      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadtestpython
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: loadtestpython
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
